# Generated by Django 2.1.5 on 2019-02-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190207_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='deta_sheet',
            new_name='data_sheet',
        ),
    ]
